GBCSportingWeb/Models/Technician.cs
using System.ComponentModel.DataAnnotations;

namespace GBCSportingWeb.Models
{
    public class Technician
    {
        [Key]
        public int TechnicianId { get; set; }

        [Required(ErrorMessage = "Please enter a Name")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter an Email")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Please enter a Phone Number")]
        public string? Phone { get; set; }

    }
}

GBCSportingWeb/Controllers/TechIncidentController.cs
using GBCSportingWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace GBCSportingWeb.Controllers
{
    public class TechIncidentController : Controller
    {

        private ApplicationDbContext context { get; set; }

        public TechIncidentController(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult ShowTechnicians()
        {
            ViewBag.Technicians = context.Technicians.OrderBy(t => t.TechnicianId).ToList();

            return View("Technicians");
        }

        [HttpPost]
        public IActionResult IncidentsByTechnician(Technician technician)
        {
            if (technician.TechnicianId == 0)
            {
                TempData["Error"] = "Please select a Technician";
                return RedirectToAction("ShowTechnicians");
            }

            int id = technician.TechnicianId;

            HttpContext.Session.SetInt32("TechId", id);

            //Filter for incidents with technician id that equals one in argument 
            var incidents = context.Incidents.OrderBy(i => i.IncidentId).Where(t => t.TechnicianId == technician.TechnicianId).Where(t => t.DateClosed == null).ToList();
            ViewBag.Technician = context.Technicians.Find(technician.TechnicianId);
            ViewBag.Products = context.Products.OrderBy(p => p.ProductId).ToList();
            ViewBag.Customers = context.Customers.OrderBy(c => c.CustomerId).ToList();


            return View("IncidentsByTechnician", incidents);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var incident = context.Incidents.Find(id);
            ViewBag.CustomerName = context.Customers.Find(incident.CustomerId).FirstName;
            ViewBag.CustomerName += " " + context.Customers.Find(incident.CustomerId).LastName;
            ViewBag.TechnicianName = context.Technicians.Find(incident.TechnicianId).Name;
            ViewBag.ProductName = context.Products.Find(incident.ProductId).ProductName;
            ViewBag.Title = incident.Title;            
            ViewBag.DateOpened = incident.DateOpened;
            return View(incident);
        }

        [HttpPost]
        public IActionResult Edit(Incident incident)
        {
            if (ModelState.IsValid)
            {
                
                context.Incidents.Update(incident);
                context.SaveChanges();
                int num = (int)HttpContext.Session.GetInt32("TechId");
                var technician = context.Technicians.Find(num);
                return IncidentsByTechnician(technician);
            }
            else
            {
                return Edit(incident.IncidentId);
            }
        }

        [HttpGet]
        public IActionResult Cancel()
        {
            int num = (int)HttpContext.Session.GetInt32("TechId");
            var technician = context.Technicians.Find(num);
            return IncidentsByTechnician(technician);
        }
    }
}

GBCSportingWeb/Controllers/TechnicianController.cs
using GBCSportingWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace GBCSportingWeb.Controllers
{
    public class TechnicianController : Controller
    {
        private ApplicationDbContext context { get; set; }

        public TechnicianController(ApplicationDbContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var Technicians = context.Technicians
                            .OrderBy(t => t.Name)
                            .ToList();

            //Sets a session cookie for storing the active nav link
            HttpContext.Session.SetString("Active", "Technicians");

            return View(Technicians);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Action = "Add";
            return View("Edit", new Technician());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            
            var technician = context.Technicians.Find(id);
            return View(technician);
        }

        [HttpPost]
        public IActionResult Edit(Technician technician)
        {
            if (ModelState.IsValid)
            {
                if (technician.TechnicianId == 0)
                    context.Technicians.Add(technician);
                else
                    context.Technicians.Update(technician);
                context.SaveChanges();
                return RedirectToAction("Index", "Technician");
            }
            else
            {
                ViewBag.Action = (technician.TechnicianId == 0) ? "Add" : "Edit";
                return View(technician);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var technician = context.Technicians.Find(id);

            //Have to load incidents if we want to cascade down and remove technicians from incidents 
            var incidents = context.Incidents.ToList();
            context.Technicians.Remove(technician);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }

}

GBCSportingWeb/Views/TechIncident/Edit.cshtml
@model Incident



<div class="flex flex-col justify-center items-center mt-36 mb-10">
    <h1 class="mb-20 text-4xl">Edit Incident</h1>
    <div class="bg-neutral sm:w-6/12 md:w-4/12  pt-10 pb-10 rounded-lg ">

        <div class=" ml-5 ">

            <form asp-action="Edit" method="post">
                <div asp-validation-summary="All" ></div>

                <div class="mt-5 flex ">
                    <h2>Technician: </h2>
                    <h2  class="ml-8">@ViewBag.TechnicianName</h2>
                </div>

                <div class="mt-5 flex ">
                    <h2>Customer: </h2>
                    <h2 class="ml-10">@ViewBag.CustomerName</h2>
                </div>

                <div class="mt-5 flex ">
                    <h2>Product: </h2>
                    <h2 class="ml-12 pl-1.5">@ViewBag.ProductName</h2>
                </div>


                <div class="mt-5 flex">
                    <h2>Title: </h2>
                    <h2 class="ml-8">@ViewBag.Title</h2>
                </div>

                <div class="mt-5 flex">
                    <h2>Date Opened: </h2>
                    <h2 class="ml-8">@ViewBag.DateOpened</h2>
                </div>

                <div class="mt-5">
                    <label asp-for="Description" class="label">
                        <span class="label-text">Description</span>
                    </label>
                    <input asp-for="Description" type="text" placeholder="Type here" class="input w-6/12 ">
                </div>            


                <div>
                    <label asp-for="DateClosed" class="label mt-5">
                        <span class="label-text">Date Closed</span>
                    </label>
                    <input class="rounded-lg p-2 input w-6/12" type="date" asp-for="DateClosed" />
                </div>

                <input type="hidden" asp-for="IncidentId"/>
                <input type="hidden" asp-for="ProductId"/>
                <input type="hidden" asp-for="CustomerId"/>
                <input type="hidden" asp-for="TechnicianId"/>
                <input type="hidden" asp-for="Title"/>


                <button  class="btn btn-primary mt-5">Save</button>
                <a asp-controller="TechIncident" asp-action="Cancel" class="btn btn-outline btn-error" >Cancel</a>
            </form>
         </div>
    </div>
</div>

GBCSportingWeb/Views/TechIncident/IncidentsByTechnician.cshtml
@model List<Incident>
@using Microsoft.AspNetCore.Http




<div class="card flex justify-center items-center mt-36 ">

    <div class="mb-20">
        <h1 class=" text-4xl ">Incidents By @ViewBag.Technician.Name
        </h1>
    </div>

        @if (Model.Count != 0)
        {
            <div class="w-7/12 overflow-x-auto sm:overflow-auto  ">
                <table class="table w-full table-zebra">
                    <thead>
                        <tr >
                            <th class="bg-primary  border-r-2 border-gray-700">Title</th>
                            <th class="bg-primary border-r-2 border-gray-700">Customer</th>
                            <th class="bg-primary border-r-2 border-gray-700">Product</th>
                            <th class="bg-primary">Date Opened</th>
                            <th class="bg-primary"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var incident in Model)
                        {
                            <tr>
                                <th>@incident.Title</th>
                                <td>@incident.Customer.FirstName</td>
                                <td>@incident.Product.ProductName</td>
                                <td>@incident.DateOpened</td>   
                                <td><a asp-controller="TechIncident" asp-action="Edit" asp-route-id="@incident.IncidentId" ><i class="fa-solid fa-pen-to-square"></i></a></td>
                            </tr>
                        }         

                    </tbody>
                </table>

        
                <a asp-controller="TechIncident" asp-action="ShowTechnicians" class="btn btn-primary mt-10" >Switch Technician</a>
            </div>
            }
        else
            {
                <div class="text-4xl text-red-400">There are no open Incidents assigned to this Technician</div>
                <a asp-controller="TechIncident" asp-action="ShowTechnicians" class="btn btn-primary mt-10" >Switch Technician</a>
            }


    
</div>

GBCSportingWeb/Views/TechIncident/Technicians.cshtml
@model Technician
@{
}
<div class="flex flex-col justify-center items-center mt-36">
    <h1 class="mb-20 text-4xl">Test</h1>
    <div class="bg-neutral w-3/12  pt-10 pb-10 rounded-lg ">

        <div class=" ml-5 ">

            <form asp-controller="TechIncident" asp-action="IncidentsByTechnician" method="post">
                <div asp-validation-summary="All" ></div>
                    
                @if (TempData.Keys.Contains("Error"))
                    {
                        <span class="text-red-400">@TempData["Error"]</span>
               
                    }
               
                <div class="mt-5">
                    <label asp-for="TechnicianId" class="label">
                        <span class="label-text">Technician</span>
                    </label>
                    <select asp-for="TechnicianId" class="select w-9/12">
                        <option disabled selected>Choose a Technician</option>
                        @foreach(Technician t in ViewBag.Technicians)
                        {
                            <option value="@t.TechnicianId">@t.Name</option>
                        }
                    </select>
                    
                </div>
                



                <button  class="btn btn-primary mt-5">Select</button>

            </form>
         </div>
    </div>
</div>