GBCSportingWeb/Controllers/CustomerController.cs
using GBCSportingWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GBCSportingWeb.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext context { get; set; }

        public CustomerController(ApplicationDbContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()  
        {
            var customers = context.Customers
                            .OrderBy(c => c.FirstName).ThenBy(c => c.LastName)
                            .ToList();

            //Sets a session cookie for storing the active nav link
            HttpContext.Session.SetString("Active", "Customers");

            return View(customers);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Action = "Add";
            var countries = context.Countries.OrderBy(c => c.CountryId).ToList();

            ViewBag.Countries = countries;

            return View("Edit", new Customer());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var countries = context.Countries.OrderBy(c => c.CountryId).ToList();
            var customer = context.Customers.Find(id);
            ViewBag.Countries = countries;
            return View(customer);
        }
        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            

            if (ModelState.IsValid)
            {
                if (customer.CustomerId == 0)
                {
                    //The folllowing code checks if the email entered is already in the system

                    string key = nameof(Customer.Email);

                    if (ModelState.GetValidationState(key) == ModelValidationState.Valid)
                    {
                        var email = customer.Email;
                        var customers = context.Customers.ToList();
                        bool inSystem = false;
                        foreach (var cus in customers)
                        {
                            if (email == cus.Email)
                            {
                                inSystem = true; break;
                            }
                        }
                        if (inSystem)
                        {
                            ModelState.AddModelError(key, "Email is already in use.");
                        }
                        else
                        {
                            context.Customers.Add(customer);
                        }
                    }

                }
                else
                {
                    context.Customers.Update(customer);
                    
                }
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Action = (customer.CustomerId == 0) ? "Add" : "Edit";
                ViewBag.Countries = context.Countries.OrderBy(c => c.CountryId).ToList();
                return View(customer);
            }   
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var customer = context.Customers.Find(id);
            context.Customers.Remove(customer);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

GBCSportingWeb/Controllers/IncidentController.cs
using GBCSportingWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;


namespace GBCSportingWeb.Controllers
{
    public class IncidentController : Controller
    {

        private ApplicationDbContext context { get; set; }

        public IncidentController(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index(string filter = "all")
        {
            //Instantiates a viewlistmodel and populates the lists from the db context
            var data = new IncidentListViewModel
            {
                IncidentFilter = filter,
                Incidents = context.Incidents.ToList(),
                Products = context.Products.ToList(),
                Technicians = context.Technicians.ToList(),
                Customers = context.Customers.ToList(),
            };

            //Adds a query to the incidents list if a filter was passed to the index method. 
            IQueryable<Incident> query = context.Incidents;
            if(filter == "open")
            {
                query = query.Where(
                    i => i.DateClosed == null);
                data.IncidentFilter = "open";
            }
            if (filter == "unassigned")
            {
                query = query.Where(
                    i => i.Technician.TechnicianId == null);
                data.IncidentFilter = "unassigned";
            }

            data.Incidents = query.ToList();

            //Sets a session cookie for storing the active nav link
            HttpContext.Session.SetString("Active", "Incidents");

            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {

            var data = new IncidentListViewModel
            {
                Products = context.Products.ToList(),
                Technicians = context.Technicians.ToList(),
                Customers = context.Customers.ToList(),
                Incident = new Incident(),
                Operation = "add"
            };

            return View("Edit", data);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = new IncidentListViewModel
            {
                Products = context.Products.ToList(),
                Technicians = context.Technicians.ToList(),
                Customers = context.Customers.ToList(),
                Incident = context.Incidents.Find(id),
                Operation = "edit"
            };

            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(IncidentListViewModel incidentListView)
        {

            if (ModelState.IsValid)
            {
                if(incidentListView.Incident.IncidentId == 0)
                {
                    //If no dateOpened was specified in the form, a datetime of Now is added
                    if(incidentListView.Incident.DateOpened == null)
                    {
                        incidentListView.Incident.DateOpened = DateTime.Now;
                    }

                    context.Incidents.Add(incidentListView.Incident);
                    context.SaveChanges();
                }
                else
                {
                    context.Incidents.Update(incidentListView.Incident);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
            {
                var data = new IncidentListViewModel
                {
                    Products = context.Products.ToList(),
                    Technicians = context.Technicians.ToList(),
                    Customers = context.Customers.ToList(),
                    Incident = context.Incidents.Find(incidentListView.Incident.IncidentId),
                    Operation = (incidentListView.Incident.IncidentId == 0) ? "Add" : "Edit"
                };

                return View(data);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var incident = context.Incidents.Find(id);
            context.Incidents.Remove(incident);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

GBCSportingWeb/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using GBCSportingWeb.Models;
using Microsoft.EntityFrameworkCore;

namespace GBCSportingWeb.Controllers
{
    public class RegistrationController : Controller
    {

        private ApplicationDbContext context { get; set; }

        public RegistrationController(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult ShowCustomers()
        {
            ViewBag.Customers = context.Customers.OrderBy(c => c.CustomerId).ToList();

            //Sets a session cookie for storing the active nav link
            HttpContext.Session.SetString("Active", "Registrations");

            return View("Customers");
        }

        [HttpPost]
        public IActionResult RegistrationsByCustomer(Customer customer)
        {
            if (customer.CustomerId == 0)
            {
                TempData["Error"] = "Please select a Customer";
                return RedirectToAction("ShowCustomers");
            }

            int id = customer.CustomerId;

            var cus = context.Customers.Find(id);

            string name = cus.FirstName + " " + cus.LastName;

            ////Sets a session cookie for storing the customer so that on redirect back, the customer info is saved
            HttpContext.Session.SetInt32("CustomerId", id);
            HttpContext.Session.SetString("CustomerName", name);
            ViewData["id"] = HttpContext.Session.GetInt32("CustomerId");

            ViewBag.Products = context.Products.OrderBy(p => p.ProductId).ToList();
            ViewBag.Registrations = context.Registrations.Where(c => c.CustomerId == customer.CustomerId).Include(p => p.Product).ToList();         

            return View("Registrations");
        }

        [HttpPost]
        public IActionResult Register(Registration registration)
        {
            //Gets the customerId from the session cookie stored earlier
            int customerId = (int)HttpContext.Session.GetInt32("CustomerId");

            var cus = context.Customers.Find(customerId);

            if(registration.ProductId == 0)
            {
                TempData["Error"] = "Please select a Product";
                return RegistrationsByCustomer(cus);
            }

            context.Registrations.Add(registration);
            context.SaveChanges();

            return RegistrationsByCustomer(cus);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var registration = context.Registrations.Find(id);
            context.Registrations.Remove(registration);
            context.SaveChanges();

            int customerId = (int)HttpContext.Session.GetInt32("CustomerId");

            var cus = context.Customers.Find(customerId);

            return RegistrationsByCustomer(cus);
        }
    }
}

GBCSportingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GBCSportingWeb</title>
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />
    @*<script src="https://unpkg.com/alpinejs@3.9.0/dist/cdn.min.js" defer></script>*@
    <script src="https://unpkg.com/alpinejs" defer></script>

    @*<link rel="stylesheet" href="~/GBCSportingWeb.styles.css" asp-append-version="true" />*@
</head>

@{
    string active = Context.Session.GetString("Active");
}

<body>
    <div class="navbar mb-2 shadow-lg bg-neutral text-neutral-content rounded-box overflow-x-auto sm:overflow-auto">
        <div class="px-2 mx-2 navbar-start">
            <div>
                <span class="text-lg font-bold">
                GBC Sporting
                </span>
                <i class="fa-solid fa-volleyball"></i>
            </div>            
        </div>
        <div class=" px-2 mx-2 navbar-center lg:flex">
            <div class="flex items-stretch">
                <a class="@(active == "Home" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Home" asp-action="Index">
                    Home
                </a>
                <a class="@(active == "Products" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )"  asp-controller="Product" asp-action="Index">
                    Products
                </a>
                <a class="@(active == "Technicians" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Technician" asp-action="Index">
                    Technicians
                </a>
                <a class="@(active == "Customers" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Customer" asp-action="Index">
                    Customers
                </a>
                <a class="@(active == "Incidents" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Incident" asp-action="Index">
                    Incidents
                </a>
                <a class="@(active == "Registrations" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Registration" asp-action="ShowCustomers">
                    Registrations
                </a>
                <a class="@(active == "About" ?  "btn btn-ghost btn-sm rounded-btn btn-active" : "btn btn-ghost btn-sm rounded-btn" )" asp-controller="Home" asp-action="About">
                    About
                </a>
            </div>
        </div>
        <div class="navbar-end">
            <button class="btn btn-square btn-ghost">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
                </svg>
            </button>
            <button class="btn btn-square btn-ghost">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
        </div>
    </div>

    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/4fcb81c091.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
    
</body>

</html>